import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Payment, DailySummary } from "@/models/payment";
import { formatCentstoDisplayCurrency } from "@/utils/formatCurrency";

export async function exportDailySummaryAsPdf(
    summary: DailySummary,
    payments: Payment[],
    date: string
): Promise<void> {
    const paymentRows = payments
        .map(
            (p) => `
        <tr>
            <td>${p.merchantName}</td>
            <td>${p.category}</td>
            <td>•••• ${p.cardLastFourDigits}</td>
            <td>${formatCentstoDisplayCurrency(p.amountInCents)}</td>
        </tr>`
        )
        .join("");

    const htmlContent = `
    <html>
    <head>
        <meta charset="utf-8" />
        <style>
            body {
                font-family: -apple-system, Arial, sans-serif;
                padding: 30px;
                color: #333;
            }
            h1 {
                color: #1A1A2E;
                border-bottom: 3px solid #4ADE80;
                padding-bottom: 10px;
            }
            .summary-box {
                background: #F5F5F5;
                border-radius: 12px;
                padding: 20px;
                margin: 20px 0;
                display: flex;
                justify-content: space-between;
            }
            .stat { text-align: center; }
            .stat-value { font-size: 24px; font-weight: bold; color: #4ADE80; }
            .stat-label { font-size: 12px; color: #888; margin-top: 4px; }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }
            th {
                background-color: #4ADE80;
                color: #000;
                padding: 12px 8px;
                text-align: left;
                font-weight: 600;
            }
            td {
                border-bottom: 1px solid #eee;
                padding: 10px 8px;
            }
            tr:nth-child(even) { background-color: #fafafa; }
            .footer {
                margin-top: 30px;
                text-align: center;
                color: #aaa;
                font-size: 11px;
            }
        </style>
    </head>
    <body>
        <h1>TapTrack — Daily Summary</h1>
        <p><strong>Date:</strong> ${date}</p>

        <div class="summary-box">
            <div class="stat">
                <div class="stat-value">${formatCentstoDisplayCurrency(summary.totalSpentInCents)}</div>
                <div class="stat-label">Total Spent</div>
            </div>
            <div class="stat">
                <div class="stat-value">${summary.transactionCount}</div>
                <div class="stat-label">Transactions</div>
            </div>
            <div class="stat">
                <div class="stat-value">${formatCentstoDisplayCurrency(summary.averagePaymentInCents)}</div>
                <div class="stat-label">Average</div>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Merchant</th>
                    <th>Category</th>
                    <th>Card</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                ${paymentRows}
            </tbody>
        </table>

        <div class="footer">Generated by TapTrack</div>
    </body>
    </html>
    `;

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        dialogTitle: "Share Daily Summary",
        UTI: "com.adobe.pdf",
    });
}